name: Build Enovy and push on DockerHub 
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build Envoy image
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: aakatev/envoy-fips:v1.16-latest
        load: true

    - name: Push Envoy image
      run: docker push aakatev/envoy-fips:v1.16-latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
